//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Proyectos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        public decimal IDACTIVIDAD { get; set; }
        public Nullable<int> IDPROYECTO { get; set; }
        public string NOMBREACT { get; set; }
        public string DESCRIPCIONACT { get; set; }
    }
}
