//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Proyectos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        public decimal IDTAREA { get; set; }
        public Nullable<int> IDACTIVIDAD { get; set; }
        public string NOMBRETAREA { get; set; }
        public string DESCRIPCIONT { get; set; }
        public System.DateTime FECHAINIT { get; set; }
        public System.DateTime FECHAFINT { get; set; }
    }
}
